//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdateCrd) DeepCopyInto(out *RollingUpdateCrd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdateCrd.
func (in *RollingUpdateCrd) DeepCopy() *RollingUpdateCrd {
	if in == nil {
		return nil
	}
	out := new(RollingUpdateCrd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RollingUpdateCrd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdateCrdList) DeepCopyInto(out *RollingUpdateCrdList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RollingUpdateCrd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdateCrdList.
func (in *RollingUpdateCrdList) DeepCopy() *RollingUpdateCrdList {
	if in == nil {
		return nil
	}
	out := new(RollingUpdateCrdList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RollingUpdateCrdList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdateCrdSpec) DeepCopyInto(out *RollingUpdateCrdSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdateCrdSpec.
func (in *RollingUpdateCrdSpec) DeepCopy() *RollingUpdateCrdSpec {
	if in == nil {
		return nil
	}
	out := new(RollingUpdateCrdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdateCrdStatus) DeepCopyInto(out *RollingUpdateCrdStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdateCrdStatus.
func (in *RollingUpdateCrdStatus) DeepCopy() *RollingUpdateCrdStatus {
	if in == nil {
		return nil
	}
	out := new(RollingUpdateCrdStatus)
	in.DeepCopyInto(out)
	return out
}
