---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - demo.roll.io
  resources:
  - rollingupdatecrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.roll.io
  resources:
  - rollingupdatecrds/finalizers
  verbs:
  - update
- apiGroups:
  - demo.roll.io
  resources:
  - rollingupdatecrds/status
  verbs:
  - get
  - patch
  - update
