# permissions for end users to view rollingupdatecrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollingupdatecrd-viewer-role
rules:
- apiGroups:
  - demo.roll.io
  resources:
  - rollingupdatecrds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.roll.io
  resources:
  - rollingupdatecrds/status
  verbs:
  - get
