# permissions for end users to edit rollingupdatecrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollingupdatecrd-editor-role
rules:
- apiGroups:
  - demo.roll.io
  resources:
  - rollingupdatecrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.roll.io
  resources:
  - rollingupdatecrds/status
  verbs:
  - get
